exports.noOfSensors = 3;
exports.msgSize = 5;
exports.msg_len = exports.msgSize * exports.noOfSensors;
exports.hash_size = 16;
exports.secret_word = "S0*(dae{dse2";
exports.dbName = "ucol_wflow";
exports.collectionName = 'sensorData';
exports.dbServer = 'yknx4:konami1994@widmore.mongohq.com';
exports.dbPort = "10000";